### ISSUE TITLE
[Bug] HEALSHIPS! broken

### ISSUE THREAD

**Issue by ariefradityo** [Cryptomancerx/BGA2Editor#2]
I'm using version 1.1 editor for Steam BFGA2 Patch One version and tried to use HEALSHIPS! command but it broke the script, haven't tried to debug myself. Here is the stacktrace:

`Traceback (most recent call last):
  File "BGA2Editor.py", line 184, in <module>
  File "BGA2Editor.py", line 13, in Main
  File "BGA2Editor.py", line 118, in BGAEdit
  File "BGA2Editor.py", line 154, in EditShips
KeyError: 'Nova'`

**Comment by ariefradityo** [comment]
Nevermind, already fixed this in PR: https://github.com/Cryptomancerx/BGA2Editor/pull/3
